kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator
  namespace: demo
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator
  namespace: demo
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: AD-Group
roleRef:
  kind: Role
  name: operator
  apiGroup: rbac.authorization.k8s.io
---