apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 4.0.6
    # or with a git clone
    # git: https://github.com/kubernetes/ingress-nginx/
    # ref: helm-chart-4.0.6
    # path: charts/ingress-nginx
  values:
    controller:
      ingressClass: nginx
      kind: Deployment
      service:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        sessionAffinity: ClientIP
